# Generated by Django 3.0.5 on 2021-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210117_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refundcharges',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
