# Generated by Django 3.0.5 on 2021-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210118_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaloffering',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
