# Generated by Django 3.0.5 on 2021-01-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_educationaloffering_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eligibility',
            new_name='eligibilityHeader',
        ),
        migrations.CreateModel(
            name='eligibilityDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('eligibiltyHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.eligibilityHeader')),
            ],
        ),
    ]
