# Generated by Django 3.0.5 on 2021-01-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210118_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibilityheader',
            name='content',
        ),
        migrations.AddField(
            model_name='eligibilityheader',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligibilityheader',
            name='heading',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
