# Generated by Django 3.0.5 on 2021-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210118_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityheader',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
