# Generated by Django 3.0.5 on 2021-01-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210118_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptancePolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('degreeProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.degreeProgram')),
            ],
        ),
    ]
