# Generated by Django 3.0.5 on 2021-01-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_acceptancepolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptancepolicy',
            name='degreeProgram',
        ),
        migrations.AddField(
            model_name='acceptancepolicy',
            name='educationalOffering',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.educationalOffering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acceptancepolicy',
            name='heading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
