# Generated by Django 3.0.5 on 2021-01-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210119_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='nominationConsideration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('educationalOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.educationalOffering')),
            ],
        ),
    ]
