# Generated by Django 3.0.5 on 2021-01-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_nominationconsideration'),
    ]

    operations = [
        migrations.CreateModel(
            name='eligibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=400)),
                ('subHeading', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('degreeProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.degreeProgram')),
            ],
        ),
        migrations.RemoveField(
            model_name='eligibilityheader',
            name='degreeProgram',
        ),
        migrations.DeleteModel(
            name='eligibilityDetails',
        ),
        migrations.DeleteModel(
            name='eligibilityHeader',
        ),
    ]
