# Generated by Django 3.0.5 on 2021-01-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210119_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='eligibilityDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eligibilityHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('degreeProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.degreeProgram')),
            ],
        ),
        migrations.DeleteModel(
            name='eligibility',
        ),
        migrations.AddField(
            model_name='eligibilitydetails',
            name='eligibiltyHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.eligibilityHeader'),
        ),
    ]
