# Generated by Django 3.0.5 on 2021-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210119_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsAndUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media')),
                ('heading', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
