# Generated by Django 3.0.5 on 2021-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_gallery_homeslider_visionandmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionandmission',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visionandmission',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
