# Generated by Django 3.0.5 on 2021-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210119_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionandmission',
            name='heading',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
