# Generated by Django 3.0.5 on 2021-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210119_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='chancellorMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='visionandmission',
            name='category',
            field=models.CharField(choices=[('VISION', 'VISION'), ('MISSION', 'MISSION')], max_length=20),
        ),
    ]
