# Generated by Django 3.0.5 on 2021-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_contactquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='accreditationList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='accreditationParagraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
