# Generated by Django 3.0.5 on 2021-01-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_accreditationlist_accreditationparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='describingAccreditationParagraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField()),
                ('listAvailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='describingAccreditation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listItem', models.TextField()),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.describingAccreditationParagraph')),
            ],
        ),
    ]
