# Generated by Django 3.0.5 on 2021-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_accreditationimportance'),
    ]

    operations = [
        migrations.CreateModel(
            name='afterGraduationServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField()),
            ],
        ),
    ]
