# Generated by Django 3.0.5 on 2021-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_accreditatedcenters_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatedcenters',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
