# Generated by Django 3.0.5 on 2021-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_accreditatedcenters_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatedcenters',
            name='contactPerson',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
