# Generated by Django 3.0.5 on 2021-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20210126_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditatedcenters',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
