# Generated by Django 3.0.5 on 2021-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20210126_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatedcenters',
            name='flag',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
