# Generated by Django 3.0.5 on 2021-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20210126_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
