# Generated by Django 3.0.5 on 2021-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20210128_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='thesisPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
