# Generated by Django 3.0.5 on 2021-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_academyworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='gradeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('inclusion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='thesisEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=200)),
                ('hundread', models.TextField()),
                ('ninety', models.TextField()),
                ('eighty', models.TextField()),
                ('seventy', models.TextField()),
            ],
        ),
    ]
