# Generated by Django 3.0.5 on 2021-01-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_gradetable_thesisevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisevaluation',
            name='fail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
