# Generated by Django 3.0.5 on 2021-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_thesisevaluation_fail'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
