# Generated by Django 3.0.5 on 2021-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_studentfiles_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicsCenters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
