# Generated by Django 3.0.5 on 2021-01-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20210130_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodalcontent',
            name='title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.educationModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalmodalcontent',
            name='heading',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
