# Generated by Django 3.0.5 on 2021-01-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_auto_20210130_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonDiscriminationPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
