# Generated by Django 3.0.5 on 2021-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_nondiscriminationpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainCampus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
