# Generated by Django 3.0.5 on 2021-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_requirementcontent_requirementheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaloffering',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
