# Generated by Django 3.0.5 on 2021-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_academyworks_hyperlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantagescontent',
            old_name='content',
            new_name='contentHeading',
        ),
        migrations.AddField(
            model_name='advantagescontent',
            name='contentData',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='academyworks',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
