# Generated by Django 3.0.5 on 2021-03-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_auto_20210302_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantagescontent',
            name='header',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.advantagesHeader'),
            preserve_default=False,
        ),
    ]
